// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Form$ReactTemplate from "./Form.bs.js";
import * as Counter$ReactTemplate from "./Counter.bs.js";

function reducer(action, _state) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

function matchUrlToComponent(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "counter" : 
          if (match[1]) {
            return /* NotFoundRoute */3;
          } else {
            return /* CounterRoute */2;
          }
      case "form" : 
          if (match[1]) {
            return /* NotFoundRoute */3;
          } else {
            return /* FormRoute */0;
          }
      case "i18n" : 
          if (match[1]) {
            return /* NotFoundRoute */3;
          } else {
            return /* I18nRoute */1;
          }
      default:
        return /* NotFoundRoute */3;
    }
  } else {
    return /* CounterRoute */2;
  }
}

function changeRoute(route, _event, self) {
  return Curry._1(self[/* send */3], /* ChangeRoute */[route]);
}

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watchId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangeRoute */[matchUrlToComponent(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */2](watchId);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              var tmp;
              switch (match) {
                case 0 : 
                    tmp = ReasonReact.element(undefined, undefined, Form$ReactTemplate.make(/* array */[]));
                    break;
                case 1 : 
                    tmp = React.createElement("div", undefined);
                    break;
                case 2 : 
                    tmp = ReasonReact.element(undefined, undefined, Counter$ReactTemplate.make(/* array */[]));
                    break;
                case 3 : 
                    tmp = "NOT FOUND";
                    break;
                
              }
              return React.createElement(React.Fragment, undefined, React.createElement("h2", undefined, "ReasonReact Handbook"), React.createElement("ul", {
                              className: "nav"
                            }, React.createElement("li", {
                                  onClick: (function (_event) {
                                      return ReasonReact.Router[/* push */0]("/counter");
                                    })
                                }, "Counter"), React.createElement("li", {
                                  onClick: (function (_event) {
                                      return ReasonReact.Router[/* push */0]("/form");
                                    })
                                }, "Form"), React.createElement("li", {
                                  onClick: (function (_event) {
                                      return ReasonReact.Router[/* push */0]("/i18n");
                                    })
                                }, "I18n")), React.createElement("div", undefined, tmp));
            }),
          /* initialState */(function (param) {
              return /* record */[/* route */matchUrlToComponent(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0))];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  reducer ,
  matchUrlToComponent ,
  changeRoute ,
  component ,
  make ,
  
}
/* component Not a pure module */
